#!/run/current-system/sw/bin/sh
 

usage()  
{  
  echo "Usage: $0 site-number"  
  exit 1  
} 

if [ $# -ne 1 ] ; then
  usage
else
  site_nr=$1
fi

# create directory
configuration_dir='./ups-configs'
[ -d $configuration_dir ] || mkdir $configuration_dir

# compute ip ..
hostname=USV0${site_nr}

#------------------------------------------------------------------------------
# here document
#
cat > ${configuration_dir}/K${site_nr}.conf << eof
# hello company, here-document generated by $0 for site ${site_nr} 

[System]
hostname $hostname
[Web]
security secure

eof
